name: pw_manager
description: Simple cross-platform Flutter password manager example
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  uuid: ^3.0.7
  file_picker: ^10.3.3
  path_provider: ^2.0.15
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  crypto: ^3.0.2
  synchronized: ^3.0.0

flutter:
  uses-material-design: true
