name: pw_manager
description: Simple cross-platform Flutter password manager example
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cryptography: ^2.7.0
  file_picker: ^10.3.3
  path_provider: ^2.1.5
  synch ronized: ^3.4.0
  bitsdojo_window: ^0.1.6

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "public/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "public/logo.png"
  android: true
  ios: true